### ISSUE TITLE
OutOfMemoryError crashes app after creating multiple instances (using 5.1.0-Snapshot)

### ISSUE THREAD

**Issue by tuncakagan** [amlcurran/ShowcaseView#244]
Hi everyone,

Even though this error was reported and solved(#183), I still receive it even after upgrading to 5.1.0-Snapshot.  I'm creating six instances of ShowCaseViews one after another as a tutorial in my app, and I can only create 34 instances(that is, after starting the tutorial for the sixth time) before the app crashes.  Every time a new ShowCaseView is created, the heap is increased to a certain point that gives OutOfMemoryError and crashes the app.  I really love this library and its design and want to use it in my app, but right now the only solution seems to limit the user and only show the tutorial after the installation, but I want to enable the user to use the tutorial anytime.

Is it really solved as described in the issue given above or is there another solution that wasn't released as a snapshot? Because I can't think of a way to overcome this problem and I desperately need help.  Thanks in advance.

I am using Samsung Galaxy S3(GT-I9305) running on Android 4.3 and here is my error log:

`7583-7583/de.kisi.android.plus E/AndroidRuntime﹕ FATAL EXCEPTION: main
    java.lang.OutOfMemoryError
            at android.graphics.Bitmap.nativeCreate(Native Method)
            at android.graphics.Bitmap.createBitmap(Bitmap.java:726)
            at android.graphics.Bitmap.createBitmap(Bitmap.java:703)
            at android.graphics.Bitmap.createBitmap(Bitmap.java:670)
            at com.github.amlcurran.showcaseview.ShowcaseView.updateBitmap(ShowcaseView.java:187)
            at com.github.amlcurran.showcaseview.ShowcaseView.onGlobalLayout(ShowcaseView.java:370)
            at android.view.ViewTreeObserver.dispatchOnGlobalLayout(ViewTreeObserver.java:839)
            at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2050)
            at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1249)
            at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6364)
            at android.view.Choreographer$CallbackRecord.run(Choreographer.java:791)
            at android.view.Choreographer.doCallbacks(Choreographer.java:591)
            at android.view.Choreographer.doFrame(Choreographer.java:561)
            at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:777)
            at android.os.Handler.handleCallback(Handler.java:730)
            at android.os.Handler.dispatchMessage(Handler.java:92)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:5419)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:525)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1209)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1025)
            at dalvik.system.NativeStart.main(Native Method)`

**Comment by leisyj** [comment]
Vivekn: care to share more info on your custom state management?  I am having the same issue; I've tried re-using the ShowcaseView instance but am not having any further success curcumventing this issue.  Previous versions to 5.0 worked properly for me.

**Comment by amlcurran** [comment]
Yeah, this is a long standing issue, and one which I haven't had a good answer for yet. I'll try to have a think (and profile) this evening.

Off the top of my head, have you tried removing the ShowcaseView from the view once you have hidden it?

**Comment by hatpick** [comment]
I recently faced this issue. On some phones, it draws all the showcase views at once on top of each other in an infinite loop that causes the out of memory issue.

**Comment by GuilhermeMota93** [comment]
It happened to me aswell...
I run my app once with no problems but on the 2nd time the Out Of Memory error appears. I use the setVisibility(View.GONE) when changing views but it seems somewhere there's a leak. Is there a more efficient way of removing the views after using them?
Thank you :)

**Comment by GuilhermeMota93** [comment]
For the ones in need, i got it working by changing, in the ShowcaseView class, the bitmapBuffer from Bitmap.Config.ARG_8888 (which takes 4 bytes of memory) to Bitmap.Config.ALPHA_8 (which only takes 1 byte).
There's still a leak somewhere, and this "hack" doesn't maintain all the colors customizations made, but at least it works :D 
Waiting for a better approach! Take care ;)

**Comment by Emaadgh** [comment]
I have the same problem. any help?

**Comment by csoltenborn** [comment]
Same problem here. The problem is rather reproducable (always happens after the same number of ShocwcaseViews), so I gave Eclipse Memory Analyzer a quick shot. 

One problem seems that the CalculateTextOnPreDraw and UpdateOnGlobalLayout of ShowcaseView are only registered; since the classes are not static, they hold a reference to "their" ShowcaseView instance. A solution would be to introduce according fields, and to register and unregister the listeners e.g. in onAttachedToWindow() and onDetachedFromWindow().

I also find it surprising that the ShowcaseViews are added at creation time, but are never removed - shouldn't this happen in hide()?

Finally, the clearBitmap() method should probably look like this:

    private void clearBitmap() {
    	if (bitmapBuffer != null) {
            if (!bitmapBuffer.isRecycled()) {
                bitmapBuffer.recycle();
            }
            bitmapBuffer = null;
    	}
    }

Unfortunately, I currently don't have time to look into this any more. However, if anybody wants to jump in, I would offer to provide the dump - you just need to get MAT (Eclipse plugin or standalone version, see https://eclipse.org/mat/) and drop me a message for the download link. MAT shows 6 potential memory leaks (4 of them are ShowcaseViews) and a hint that the 4 are related, so I guess it's a good starting point. If you want to create your own dump for analysis, see e.g. http://www.vogella.com/tutorials/EclipseMemoryAnalyzer/article.html#eclipsemat_android - note that if you have installed MAT within Eclipse, creating a memory dump will do the conversion and start MAT for you, but that takes a while).

**Comment by csoltenborn** [comment]
Ok, I still looked into it :-) I might have a fix for some of the mentioned problems, see pull request https://github.com/amlcurran/ShowcaseView/pull/277

**Comment by doodlleus** [comment]
on thing that i noticed is that a heck of a lot of memory gets allocated each time createbitmap() is called. in my version i have added an additional constructor arg that takes a bitmap as an argument. so in my activity i create the bitmap once and it is used for all showcases. when im done i recycle and discard; this seems to keep the memory manageable for me.

**Comment by harshitlalpura** [comment]
@doodlleus can you please show me the code.. how have you done it ? I need it very badly.. Thanks in advance..

**Comment by doodlleus** [comment]
Ok, below is a small example of how ive achieved using multiple showcaseviews whilst maintaining memory efficiency.

Put this in your main activity where the view will go.    

    private ShowcaseView sv;
    public int currentTutorialPage = 1;
    private Bitmap showcaseBitmap;
    public void startDemoTutorial() {

        final View testtarget = findViewById(R.id.TestView);

        ViewTarget target = new ViewTarget(testtarget );
        if(sv==null)
        {
            sv = new ShowcaseView(this,true,getShowCaseBitmap());
        }

        sv.setContentTitle("Test 1/4");
        sv.setContentText("some content 1/4");
        sv.setStyle(R.style.ShowcaseView);
        sv.setOnShowcaseEventListener(new OnShowcaseEventListener() {
            @Override
            public void onShowcaseViewHide(ShowcaseView showcaseView) { currentTutorialPage = 1;  }
            @Override
            public void onShowcaseViewDidHide(ShowcaseView showcaseView) { destroyShowcase(); }
            @Override
            public void onShowcaseViewShow(ShowcaseView showcaseView) {}
        });        
        sv.setButtonText("NEXT");
        sv.setButtonPosition(getLayoutParamsTop());

        sv.overrideButtonClick(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                
                View child;
                ViewTarget target;
                int rad;

                sv.setTarget(Target.NONE);
                sv.invalidate();
                sv.show();

                switch(currentTutorialPage) {
                    case 1:
                        child = testtarget.findViewById(R.id.newtarget);
                        target = new ViewTarget(child);
                        sv.setTarget(target);
                        sv.setContentTitle("Test 2/4");
                        sv.setContentText("some content 2/4.");                        
                        sv.setButtonPosition(getLayoutParamsTop());
                        break;
                    case 2:

                        child = testtarget.findViewById(R.id.anothertarget);
                        target = new ViewTarget(child);
                        sv.setTarget(target);
                        sv.setContentTitle("Test 3/4");
                        sv.setContentText("some content 4/4.");
                        break;
                    case 3:

                        child = testtarget.findViewById(R.id.finaltarget);
                        target = new ViewTarget(child);
                        sv.setTarget(target);
                        sv.setContentTitle("Test 4/4");
                        sv.setContentText("some content 4/4.");
                        sv.setButtonText("GOT IT!");
                        sv.setButtonPosition(getLayoutParamsBottom());
                        sv.overrideButtonClick(new View.OnClickListener() {
                            @Override
                            public void onClick(View view) {
                                sv.hide();
                            }
                        });
                        break;
                }
                currentTutorialPage++;
            }
        });
        sv.showButton();
        sv.setTarget(target,false);
        addShowcase();       
    }

    private void addShowcase() {        
        ((ViewGroup) getWindow().getDecorView()).addView(sv);
        sv.show();
    }

    private Bitmap getShowCaseBitmap()
    {
        if(showcaseBitmap==null)
        {
            int w = getWindow().getDecorView().getWidth();
            int h = getWindow().getDecorView().getHeight();
            showcaseBitmap = Bitmap.createBitmap(w, h, Bitmap.Config.ARGB_8888);
        }
        return showcaseBitmap;
    }

    private void destroyShowcase() {
        if(sv!=null)
        {
            ((ViewGroup) getWindow().getDecorView()).removeView(sv);
            sv = null;            
            currentTutorialPage = 1;
        }
        currentTutorialPage = 1;
    }


you will also need to modify the showcaseview.java class

    public ShowcaseView(Context context, boolean newStyle,Bitmap bm) {
        this(context, null, R.styleable.CustomTheme_showcaseViewStyle, newStyle,bm);
    }

    protected ShowcaseView(Context context, AttributeSet attrs, int defStyle, boolean newStyle,Bitmap bm) {
        super(context, attrs, defStyle);

    if(bm==null)
    {
        bm = Bitmap.createBitmap(getMeasuredWidth(), getMeasuredHeight(), Bitmap.Config.ARGB_8888);
    }
    ....
    ....
    }
    
also, remove all calls to update bitmap.

Hope this helps

**Comment by mattiasbe** [comment]
Actually csoltenborn's pull request above #277 together with this solved it entirely (quite easy to see in Android Studio's Memory Monitor):
The pull request was needed but not enough for me to get rid of the out of memory errors. I also had to add this to all didHide events: 
```
.setShowcaseEventListener(new OnShowcaseEventListener() {

                            @Override
                            public void onShowcaseViewShow(final ShowcaseView scv) {
                            }

                            @Override
                            public void onShowcaseViewHide(final ShowcaseView scv) {
                            }

                            @Override
                            public void onShowcaseViewDidHide(final ShowcaseView scv) {
                                commonHide(scv);
                                show2(activity);
                            }

                        })

static void commonHide(ShowcaseView scv) {
        scv.setOnClickListener(null);
        scv.setOnShowcaseEventListener(null);
        scv.setOnTouchListener(null);
    }
```

**Comment by madcyph3r** [comment]
For me it works very well, if i comemnt out the follow line.

```java
private class UpdateOnGlobalLayout implements ViewTreeObserver.OnGlobalLayoutListener {

        @Override
        public void onGlobalLayout() {
            if (!shotStateStore.hasShot()) {
            //    updateBitmap(); // works very well, is this comment out
            }
        }
    }
```

**Comment by ramannanda9** [comment]
It is fixed took some effort. It is a guaranteed fix few things need to be changed in hide method.

First the fatal flaw that you are committing is doing View.Gone in hide method. Okay, so that does hide the view but does not remove it from the ViewGroup. You need to explicitly do that. This was a major issue.

Also While doing heap analysis, I found out that certain listeners are attached but never removed. This is a minor issue, but the changes are mentioned below.

The method hideImmediate becomes. 
public void hideImmediate() {
isShowing = false;
setVisibility(GONE);
//removeView(ShowcaseView.this);
//even better 
((ViewGroup)mActivity.getWindow().getDecorView()).removeView(ShowcaseView.this);
}

The method hide becomes

@Override
public void hide() {
clearBitmap();
// If the type is set to one-shot, store that it has shot
shotStateStore.storeShot();
mEventListener.onShowcaseViewHide(this);
fadeOutShowcase();
getViewTreeObserver().removeOnPreDrawListener(draw);
if(Build.VERSION.SDK_INT>15){
getViewTreeObserver().removeOnGlobalLayoutListener(globalLayout);
}
else {
getViewTreeObserver().removeGlobalOnLayoutListener(globalLayout);
}
//removeView(ShowcaseView.this);
//even better
((ViewGroup)mActivity.getWindow().getDecorView()).removeView(ShowcaseView.this);
}

I have also created a gist for this class.

https://gist.github.com/ramannanda9/7bf837f535b0ba2b96f2#file-showcaseview-java

Feel free to merge the changes.

Here is a detailed analysis on this issue. 

http://ramannanda.blogspot.in/2015/04/analyzing-memory-leaks-in-android.html

**Comment by eyal-fairfly** [comment]
Hi,

I am also getting an OOM error: Throwing OutOfMemoryError "Failed to allocate a 7672332 byte allocation with 7074500 free bytes and 6MB until OOM" with the error tracing back to create Bitmap. See full log below.

I am only creating one ShowcaseView and the problem is when I toggle back and forth between states that require / don't require the ShowcaseView, in the 3rd or 4th time I am getting the error. 

Anyone else still experiencing this issue?

Full log:

    java.lang.OutOfMemoryError: Failed to allocate a 7672332 byte allocation with 7074500 free bytes and 6MB until OOM
            at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
            at android.graphics.Bitmap.nativeCreate(Native Method)
            at android.graphics.Bitmap.createBitmap(Bitmap.java:812)
            at android.graphics.Bitmap.createBitmap(Bitmap.java:789)
            at android.graphics.Bitmap.createBitmap(Bitmap.java:756)
            at com.github.amlcurran.showcaseview.ShowcaseView.updateBitmap(ShowcaseView.java:169)
            at com.github.amlcurran.showcaseview.ShowcaseView.onGlobalLayout(ShowcaseView.java:351)
            at android.view.ViewTreeObserver.dispatchOnGlobalLayout(ViewTreeObserver.java:912)
            at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1881)
            at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1061)
            at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5885)
            at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
            at android.view.Choreographer.doCallbacks(Choreographer.java:580)
            at android.view.Choreographer.doFrame(Choreographer.java:550)
            at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5254)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

**Comment by mattiasbe** [comment]
I tried using 5.3.0 again (instead of the pull request mentioned in my previous comment and nulling the listeners I mention there as well which works great). I get the Out of memory again unfortunately, so problem still there.

**Comment by mattiasbe** [comment]
So @amlcurran would be great to have pull request #277 in still (removing viewtree obsverver listeners etc).

**Comment by amlcurran** [comment]
I'm currently making some changes as those listeners aren't actually needed any more. And I can't find memory leaks any more. I'll do some more testing and report back!

**Comment by mattiasbe** [comment]
Sounds great!

**Comment by amlcurran** [comment]
Can you tell me what device you're using and how you reproduce the out of memory? That would be really useful!

**Comment by mattiasbe** [comment]
Sure of course @amlcurran. I tried this on a Nexus 6 with M, stock for the test the other day. In February we tried it on a wide range of devices  and android versions and all with the same problem.
With the pull request and additional nulling out of listeners it has been fine for all users ever since.

To reproduce we just do  new ShowCase.Builder() after each other when one is dismessed. Memory usage quickly goes up for each one and after about 8 or so I got OOM on the Nexus 6 (rather large app heap on that one).

Something along these lines:

```java
new ShowcaseView.Builder(activity, useNewStyle)
                        .setTarget(new ViewTarget(R.id.action_start, activity))
                        .setContentTitle(R.string.tutorial_recording_title)
                        .setContentText(R.string.tutorial_recording_text)
                        .setShowcaseEventListener(new OnShowcaseEventListener() {
                        @Override
                            public void onShowcaseViewDidHide(final ShowcaseView scv) {
                                commonHide(scv);
                                showTutorialRecordingNextStop(activity);

...

static void commonHide(ShowcaseView scv) {
        scv.setOnClickListener(null);
        scv.setOnShowcaseEventListener(null);
        scv.setOnTouchListener(null);
    }

```

**Comment by ramannanda9** [comment]
Hi,

Did anyone try my fix. The fix that I wrote. The memory is not released
because decorview still holds reference to the object.

Regards
Ramandeep

**Comment by amlcurran** [comment]
@mattiasbe thank you very much that is really useful. I looked the other day and couldn't find any memory leaks but will try with what you suggested. Reopening the bug for now

**Comment by amlcurran** [comment]
@mattiasbe I have hopefully fixed the issues, could you try using 5.4.0-SNAPSHOT and see if you're still having issues?

**Comment by PipperPublishing** [comment]
Tried the 5.4.0-SNAPSHOT yesterday (12-Nov). Looks good. See my comment https://github.com/amlcurran/ShowcaseView/pull/322

**Comment by mattiasbe** [comment]
@amlcurran unfortunately I'm not in the office until Wednesday again,  I'll see if I can test it anyway before that. But sounds great,  thanks!

**Comment by amlcurran** [comment]
Not to worry! I'll wait until I can confirm this fixes your issues before
promoting to a stable build, just let me know when you've had time to test!

Thanks

**Comment by mattiasbe** [comment]
@amlcurran  5.4.0-SNAPSHOT looks good. 5.3.0 ends with Out of memory exceptions (memory monitor shows steady increase), 5.4.0 doesn't. Remote ADB and VPN is great stuff a friday evening :)
Thanks!

**Comment by amlcurran** [comment]
Wooo! I will release that version to stable sometime in the next couple of days then, and will let you know. Thanks for investigating!

**Comment by amlcurran** [comment]
Have just released 5.4.0, thank you for all your help!

**Comment by mattiasbe** [comment]
Great,  thanks for your hard work.
